import { Link } from 'react-router-dom';
import { ArrowRight, Plus, FileText, Send, NotebookPen, FolderOpen, Tags } from 'lucide-react';
import { operations, type Article } from '../api';
import { useQuery } from '../session';
import { Badge, date, Empty, Loading, Message } from '../components/ui';
type Count = { aggregate: { count: number } };
interface Overview { total: Count; published: Count; drafts: Count; recent: Article[]; tags: {id:string}[]; categories: {id:string}[] }
export default function Dashboard(){
  const {data,error,loading,reload}=useQuery<Overview>(operations.dashboard);
  return <><div className="page-heading"><div><span className="eyebrow">OVERVIEW</span><h1>工作台</h1><p>欢迎回来，今天也有值得记录的故事。</p></div><Link className="button primary" to="/articles/new"><Plus size={18}/>写文章</Link></div><section className="welcome-banner"><div><span className="banner-label">每个想法，都值得被看见</span><h2>让记录成为习惯。</h2><p>从一篇草稿开始，慢慢构建你的知识花园。</p><Link to="/articles/new">开始创作 <ArrowRight size={17}/></Link></div><div className="banner-art" aria-hidden="true"><div className="paper"><Pen/><span/><span/><span/></div><div className="floating-plus">✦</div></div></section>{error && <Message>{error}<button onClick={reload}>重试</button></Message>}{loading ? <Loading/> : data && <><section className="stats" aria-label="内容统计">{[{label:'全部文章',value:data.total.aggregate.count,icon:FileText,color:'blue',to:'/articles'},{label:'已发布',value:data.published.aggregate.count,icon:Send,color:'green',to:'/articles?status=published'},{label:'草稿',value:data.drafts.aggregate.count,icon:NotebookPen,color:'amber',to:'/articles?status=draft'},{label:'内容分类',value:data.categories.length,icon:FolderOpen,color:'purple',to:'/categories'}].map(item=><Link to={item.to} className="stat-card" key={item.label}><div><span>{item.label}</span><strong>{item.value}</strong><small>{item.label==='草稿'?'等待打磨的想法':'持续记录，慢慢积累'}</small></div><span className={`stat-icon ${item.color}`}><item.icon size={22}/></span></Link>)}</section><div className="dashboard-grid"><section className="panel"><div className="panel-head"><div><h2>最近更新</h2><p>继续上次的思考</p></div><Link to="/articles" className="text-link">全部文章 <ArrowRight size={16}/></Link></div>{data.recent.length ? <div className="recent-list">{data.recent.map(article=><Link key={article.id} to={`/articles/${article.id}`} className="recent-row"><span className="document-icon"><FileText size={20}/></span><div className="recent-title"><strong>{article.title}</strong><small>{article.type?.name || '未分类'} · {date(article.updatedAt)}</small></div><Badge published={article.isPublished}/><ArrowRight size={16} className="muted"/></Link>)}</div>:<Empty title="从第一篇文章开始"><Link to="/articles/new" className="text-link">记录你的第一个想法 →</Link></Empty>}</section><aside className="panel quick-panel"><h2>整理你的内容</h2><p className="muted">让知识井井有条</p><Link to="/categories"><span className="stat-icon purple"><FolderOpen size={20}/></span><div><strong>分类管理</strong><small>{data.categories.length} 个分类</small></div><ArrowRight size={17}/></Link><Link to="/tags"><span className="stat-icon amber"><Tags size={20}/></span><div><strong>标签管理</strong><small>{data.tags.length} 个标签</small></div><ArrowRight size={17}/></Link><div className="tip"><span>一点小建议</span><p>先写下来，再慢慢完善。草稿只有登录后的你可以看到。</p></div></aside></div></>}</>;
}
function Pen(){ return <NotebookPen size={35}/>; }
