import { useState, type FormEvent } from 'react';
import { Plus, Search, Pencil, Trash2, FolderOpen, Hash } from 'lucide-react';
import { operations, taxonomyMutation, type Taxonomy } from '../api';
import { useQuery, useSession } from '../session';
import { Empty, Loading, Message, Modal, date } from '../components/ui';
export default function Taxonomies({kind}:{kind:'tags'|'categories'}){
  const name=kind==='tags'?'标签':'分类';const Icon=kind==='tags'?Hash:FolderOpen;
  const {api}=useSession();const {data,error,loading,reload}=useQuery<{tags:Taxonomy[];categories:Taxonomy[]}>(operations.taxonomy);
  const [search,setSearch]=useState('');const [edit,setEdit]=useState<Taxonomy|undefined|null>(null);const [remove,setRemove]=useState<Taxonomy|null>(null);const [value,setValue]=useState('');const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState('');const [feedback,setFeedback]=useState('');
  const rows=(data?.[kind]||[]).filter(t=>(t.name||'').toLowerCase().includes(search.toLowerCase()));
  async function save(e:FormEvent){e.preventDefault();if(!value.trim())return;setBusy(true);setActionError('');try{await api(taxonomyMutation(kind,edit?'update':'create'),{...(edit?{where:{id:edit.id}}:{}),data:{name:value.trim()}});setEdit(null);setFeedback(`${name}已保存`);reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);} }
  async function del(){if(!remove)return;setBusy(true);setActionError('');try{await api(taxonomyMutation(kind,'delete'),{where:{id:remove.id}});setRemove(null);setFeedback(`${name}已删除`);reload();}catch(e){setActionError((e as Error).message);}finally{setBusy(false);} }
  return <><div className="page-heading"><div><span className="eyebrow">ORGANIZE YOUR IDEAS</span><h1>{name}管理 <span className="count-pill">{data?.[kind].length??'…'}</span></h1><p>{kind==='tags'?'用关键词串联灵感，让内容产生更多关联。':'为每一篇记录找到合适的位置。'}</p></div><button className="button primary" onClick={()=>{setEdit(undefined);setValue('');setActionError('');}}><Plus size={18}/>新建{name}</button></div>{feedback&&<Message success>{feedback}</Message>}<section className="panel taxonomy-panel"><div className="panel-head"><h2>全部{name}</h2><div className="searchbox"><Search size={18}/><input aria-label={`搜索${name}`} placeholder={`搜索${name}…`} value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{error?<div className="panel-body"><Message>{error}<button onClick={reload}>重试</button></Message></div>:loading?<Loading/>:rows.length?<div className="taxonomy-grid">{rows.map(t=><div className="taxonomy-card" key={t.id}><span className={`stat-icon ${kind==='tags'?'amber':'purple'}`}><Icon size={23}/></span><div className="taxonomy-info"><h3>{t.name||'未命名'}</h3><small>{t.createdAt?`创建于 ${date(t.createdAt)}`:'内容归档'}</small></div><div className="row-actions"><button className="icon-button" aria-label={`编辑 ${t.name}`} onClick={()=>{setEdit(t);setValue(t.name||'');setActionError('');}}><Pencil size={16}/></button><button className="icon-button danger-text" aria-label={`删除 ${t.name}`} onClick={()=>{setRemove(t);setActionError('');}}><Trash2 size={16}/></button></div></div>)}</div>:<Empty title={`暂无匹配的${name}`}><p>创建一个{name}，开始整理你的内容。</p></Empty>}</section>{edit!==null&&<Modal title={`${edit?'编辑':'新建'}${name}`} busy={busy} close={()=>setEdit(null)}><form onSubmit={save}><label>{name}名称<input autoFocus required maxLength={80} value={value} disabled={busy} onChange={e=>setValue(e.target.value)} placeholder={`例如：${kind==='tags'?'TypeScript':'技术笔记'}`}/></label>{actionError&&<Message>{actionError}</Message>}<div className="modal-actions"><button type="button" className="button" disabled={busy} onClick={()=>setEdit(null)}>取消</button><button className="button primary" disabled={busy||!value.trim()}>{busy?'保存中…':'保存'}</button></div></form></Modal>}{remove&&<Modal title={`删除${name}`} busy={busy} close={()=>setRemove(null)}><p className="modal-copy">删除「{remove.name}」？关联文章会保留，并移除对应的{name}关联。</p>{actionError&&<Message>{actionError}</Message>}<div className="modal-actions"><button className="button" disabled={busy} onClick={()=>setRemove(null)}>取消</button><button className="button danger" disabled={busy} onClick={del}>{busy?'删除中…':'确认删除'}</button></div></Modal>}</>;
}
